name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLISH_ARTIFACTS: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with JDK 11
        run: mvn -B install --no-transfer-progress -DskipTests

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with JDK 8
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test with JDK 11          
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Test with JDK 16         
        run: mvn -v && mvn -B test

      - name: Set up settings.xml for Sonatype
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish SNAPSHOT version to Sonatype (we can skip tests, since we only deploy, if the build workflow succeeded)
        run: mvn -v && mvn -B -P requireSnapshot --no-transfer-progress -DskipTests deploy --settings build/settings-sonatype.xml
        if: env.PUBLISH_ARTIFACTS == 'true'
        env:
          SONATYPE_USERNAME: martin.grotzke
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
